server:
  port: 8081 

debug: true
logging:
  level:
    org.springframework: DEBUG


spring:
  cloud:
    gateway:
      routes:
        - id: health_metrics
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/metrics/**,swagger-ui.html
        - id: health_metrics_swagger
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/metrics/**            

management:
  endpoints:
    web:
      exposure:
        include: "gateway"