server:
  port: 8081 
  
spring:
  cloud:
    gateway:
      routes:
        - id: error
          uri: ${ERROR_URI:http://localhost:8083}
          predicates:
            - Path=/error/**
          filters:
            - PrefixPath=/api
        - id: some_route
          uri: ${SOME_ROUTE_URI:http://localhost:8082}
          predicates:
            - Path=/some_path/**
          filters:
            - PrefixPath=/api
            - AddRequestHeader=X-Request-Red, Blue
            - AddResponseHeader=X-Response-Red, Blue

management:
  endpoints:
    web:
      exposure:
        include: "*"